wallet_node:
  btc:
    rpc_url: 'https://blockstream.info/testnet/api'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://blockstream.info/testnet/api'
    data_api_key: ''
    data_api_token: ''
    time_out: 15
  eth:
    rpc_url: 'https://eth-holesky.g.alchemy.com/v2/afSCtxPWD3NE5vSjJm2GQ'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://api-holesky.etherscan.io/api?'
    data_api_key: 'xxxx'
    data_api_token: ''
    time_out: 15
