rpc_server:
  host: 0.0.0.0
  port: 8189
http_server:
  host: 0.0.0.0
  port: 8188

chains: [Ethereum, Solana]


wallet_node:
  eth:
    rpc_url: 'https://eth-holesky.g.alchemy.com/v2/afSCtxPWD3NE5vSjJm2GQ'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://api-holesky.etherscan.io/api?'
    data_api_key: 'xxx'
    data_api_token: ''
    time_out: 15
  solana:
    rpc_url: 'https://go.getblock.io/70f479b9ed834b5f96a26934e0492b36'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://public-api.solscan.io'
    data_api_key: 'xxxx.xxx.xxx'
    data_api_token: ''
    time_out: 15
  op:
    rpc_url: 'https://eth-holesky.g.alchemy.com/v2/afSCtxPWD3NE5vSjJm2GQ'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://api-holesky.etherscan.io/api?'
    data_api_key: 'xxx'
    data_api_token: ''
    time_out: 15



network: mainnet
enable_api_cache: false


